from elasticsearch import Elasticsearch
from faker import Faker
from datetime import datetime
import random


# https://www.elastic.co/guide/en/elasticsearch/client/python-api/master/connecting.html#:~:text=When%20connecting%20to%20Elastic%20Cloud,you're%20in%20Kibana).
# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "M1ebhIUbFZYojr6jKFIj1Y68"

# Found in the 'Manage Deployment' page
CLOUD_ID = "t1:dXMtY2VudHJhbDEuZ2NwLmNsb3VkLmVzLmlvOjQ0MyQzZWY2NWYwNjVlMjE0MmVhYjQyOGQ1YmRhMzEwOTg1NiQ3YzJiMjI4OTAwMzI0ZmJhOTY4NTk4YjhkMTIzMzczZg=="

# Create the client instance
client = Elasticsearch(
    cloud_id=CLOUD_ID,
    basic_auth=("elastic", ELASTIC_PASSWORD)
)
# Successful response!
# print(client.info())
# {'name': 'instance-0000000000', 'cluster_name': ...}


index_name = 'profile6'

# # Define the employee index mapping
# mapping = {
#     "mappings": {
#         "properties": {
#             "username": { "type": "keyword" },  
#             "name": { "type": "text" }, 
#             "sex": { "type": "keyword" }, 
#             "address": { "type": "text" }, 
#             "email": { "type": "keyword" }, 
#             "birthdate": { "type": "date", "format":"yyyy-MM-dd" }, 
#             "company": { "type": "text" }, 
#             "job": { "type": "text" }, 
#             "website": { "type": "text" }
#         }
#     }
# }

# # Create the employee index with the defined mapping
# client.indices.create(index=index_name, body=mapping, ignore =400)


# Initialize Faker
fake = Faker()

# Generate 10,000 test data documents
for i in range(1000):
    
    # Generate random values for fields
    # https://faker.readthedocs.io/en/master/providers/faker.providers.profile.html
    profile = fake.profile()

    print("username: " + profile['username'])
    print("name: " + profile['name'])
    print("sex: " + profile['sex'])
    print("address: " + profile['address'])
    print("email: " + profile['mail'])
    print("birthdate: " + str(profile['birthdate']))
    print("company: " + profile['company'])
    print("job: " + profile['job'])
    print("website: " + str(profile['website']))

    
    # Create document
    doc = {
        "username": profile['username'],  
        "name": profile['name'], 
        "sex": profile['sex'], 
        "address": profile['address'], 
        "email": profile['mail'], 
        "birthdate": profile['birthdate'].strftime('%Y-%m-%d'), 
        "company": profile['company'], 
        "job": profile['job'], 
        "website": profile['website']
    }

    # Index document into Elasticsearch
    client.index(index=index_name, body=doc)

# Refresh index to ensure all documents are searchable
client.indices.refresh(index=index_name)

print("Test data indexed successfully!")


# Get the count of documents in the index
count = client.count(index=index_name)["count"]

# Print the count
print(f"There are {count} documents in the {index_name} index.")